channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=5.24.1
  - samtools =1.11
  - bedtools =2.30.0
  - gcc_linux-64=7.3.0
  - pip=21.3.1=pyhd8ed1ab_0
  - pip:
    - bio==1.3.3
    - biopython==1.79
    - biothings-client==0.2.6
    - mygene==3.2.2
    - tqdm==4.62.3
  - pandas=1.3.5=py39hde0f152_0
  - pysam=0.17.0=py39h051187c_0