channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - snakemake-minimal >=5.24.1
  - r-base=4.1
  - r-tidyverse=1.3
  - bioconductor-rtracklayer=1.52
  - bioconductor-plyranges=1.12.0
  - bioconductor-qvalue=2.24.0
  - r-optparse=1.6.6
  - r-r.utils=2.11.0